/**
 * @file A1035-Password.cpp
 * @author your name (you@domain.com)
 * @brief
 * @version 0.1
 * @date 2024-02-29
 *
 * @copyright Copyright (c) 2024
 *
 * To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.

Input Specification:
Each input file contains one test case. Each case contains a positive integer N (≤1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.

Output Specification:
For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line There are N accounts and no account is modified where N is the total number of accounts. However, if N is one, you must print There is 1 account and no account is modified instead.
 */
#include <iostream>
using namespace std;

const int N = 1010;
string name[N], pwd[N];

int m = 0; // 修改过的个数

string change(string str)
{
    string res;
    for (auto c : str)
    {
        if (c == '0')
        {
            res += '%';
        }
        else if (c == '1')
        {
            res += '@';
        }
        else if (c == 'l')
        {
            res += 'L';
        }
        else if (c == 'O')
        {
            res += 'o';
        }
        else
        {
            res += c;
        }
    }

    return res;
}

int main()
{

    int n;
    cin >> n;
    for (int i = 0; i < n; i++)
    {
        string cur_name, cur_pwd;
        cin >> cur_name >> cur_pwd;
        if (cur_pwd != change(cur_pwd))
        {
            name[m] = cur_name;
            pwd[m] = change(cur_pwd);
            m++;
        }
    }

    if (!m)
    {
        if (n == 1)
        {
            cout << "There is 1 account and no account is modified";
        }
        else
        {
            cout << "There are " << to_string(n) << " accounts and no account is modified";
        }
    }
    else
    {
        cout << m << endl;
        for (int i = 0; i < m; i++)
        {
            cout << name[i] << ' ' << pwd[i] << endl;
        }
    }
}